{{- if not (and (.Values.autoscaling.enabled) (.Capabilities.APIVersions.Has "keda.sh/v1alpha1")) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "azure-pipelines-agent.fullname" . }}
  labels:
    {{- include "azure-pipelines-agent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "azure-pipelines-agent.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount | int | required "A value for .Values.replicaCount is required" }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "azure-pipelines-agent.selectorLabels" . | nindent 8 }}
      annotations:
        # Cluster autoscaler never evicts this Pod
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
        {{- with .Values.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- $data := dict
        "restartPolicy" "Always"
        "azpAgentName" (dict "valueFrom" (dict "fieldRef" (dict "apiVersion" "v1" "fieldPath" "metadata.name" )))
      }}
      {{- include "azure-pipelines-agent.podSharedTemplate" (merge (dict "Args" $data) . ) | nindent 6 }}
{{- end }}
