{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "azure-pipelines-agent.secretName" . }}
  labels:
    {{- include "azure-pipelines-agent.labels" . | nindent 4 }}
stringData:
  personalAccessToken: {{ .Values.pipelines.personalAccessToken | quote | required "A value for .Values.pipelines.personalAccessToken is required" }}
  organizationURL: {{ .Values.pipelines.organizationURL | quote | required "A value for .Values.pipelines.organizationURL is required" }}
{{- end }}
