apiVersion: v2
name: azure-pipelines-agent
description: Deploy Azure Pipelines agent on Kubernetes. Easy way. Cheap. Windows and Linux. X64 and ARM compatible.
type: application
# Using ephemeral storage, as from Kubernetes 1.19+ (alpha)
# Explicitely specify selecting SemVer pre-version, as some providers are not following SemVer properly
# See: https://github.com/helm/helm/issues/10375#issuecomment-974203557
kubeVersion: ">= 1.19.0-0"
version: 0.0.0
appVersion: 0.0.0
icon: https://raw.githubusercontent.com/clemlesne/azure-pipelines-agent/master/docs/static/favicon.svg
keywords:
  - agent
  - auto-scale
  - azure
  - azure-devops
  - azure-pipelines
  - container
  - devops
  - docker
  - helm
  - keda
  - kubernetes
  - pipelines
  - self-hosted
  - self-hosted-agent
home: https://github.com/clemlesne/azure-pipelines-agent
sources:
  - https://github.com/clemlesne/azure-pipelines-agent
maintainers:
  - name: Clémence Lesné
    email: clemlesne@users.noreply.github.com
annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: Apache-2.0
  artifacthub.io/prerelease: "false"
