version: 2
updates:
  - package-ecosystem: github-actions
    directory: ""
    target-branch: develop
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: src/docker
    target-branch: develop
    schedule:
      interval: daily
  - package-ecosystem: gitsubmodule
    directory: cicd/version
    target-branch: develop
    schedule:
      interval: daily
