annotations:
  container.apparmor.security.beta.kubernetes.io/azp-agent: unconfined

extraVolumeMounts:
  - mountPath: /app-root/.local/share/buildkit
    name: buildkitd

extraVolumes:
  - name: buildkitd
    # emptyDir: {}
    ephemeral:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: "managed-csi-premium"
          resources:
            requests:
              storage: 16Gi

securityContext:
  seccompProfile:
    type: Unconfined
  # Has to be true for allowing RootlessKit initializing the user namespace with "newuidmap" setuid binary
  allowPrivilegeEscalation: true
  capabilities:
    # Requires more capabilities for allowing RootlessKit initializing the user namespace with "newuidmap" setuid binary.
    # TODO: Capabilities could be narrowed by keeping drop=[ALL] and whitelist the required capabilities with add=[...].
    drop: []

resources:
  limits:
    cpu: 4
    memory: 8Gi
  requests:
    cpu: 2
    memory: 4Gi

pipelines:
  capabilities:
    - arch_x64
    - buildkit
  personalAccessToken: your-pat
  poolName: private_kube
  organizationURL: https://dev.azure.com/shopping-cart-devops-demo

extraNodeSelectors:
  kubernetes.io/arch: amd64
